### ISSUE TITLE
fltk support?

### ISSUE THREAD

**Issue by inter1965** [gammasoft71/xtd_forms#1]
any possibilities to add fltk support?

**Comment by gammasoft71** [comment]
For now only wxWidgets is used as backend (native library). When xtd.forms is complete enough, Win32, gtk + and Cocoa will be added. Other libraries like Qt and fltk could also be added. Today the libraries (xtd.forms.native.win32, xtd.forms.native.gtk3, xdd.forms.native.cocoa, xtd.forms.native.qt and xdd.forms.native.fltk exist but are not implemented and evaluated.
