### ISSUE TITLE
the old project Switch is dead?

### ISSUE THREAD

**Issue by sgf** [gammasoft71/xtd_forms#2]
the old project Switch is dead?

**Comment by gammasoft71** [comment]
Yes the project is dead because there is a problem of license. But like the phenix, it is entainted to rise from its ashes in a new form: xtd (xtd_console, xtd_tunit, xtd_form, ...).
With the advantage of being much closer to modern C ++ 17 and std.

**Comment by sgf** [comment]
tks reply
