### ISSUE TITLE
[Report] broken links

### ISSUE THREAD

**Issue by graysuit** [gammasoft71/xtd_forms#3]
While reading documentation I noticed these broken links at:
https://github.com/gammasoft71/xtd_forms/blob/master/docs/tutorial.md

**Menus and toolbars
layout_management
Events
Dialogs
controls
drag & drop
Graphics
custom_controls
tetris**

Thanks so much for providing a wiki.

**Comment by gammasoft71** [comment]
Hi,

Yes, I know, the projects xtd_forms, xtd_console, xtd_... have been merged into xtd <https://github.com/gammasoft71/xtd>. I still have to clean and archive them.

Regards,
Gammasoft

**Comment by graysuit** [comment]
No problem then. Thanks for your time.
